"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { BESTIARY, DEFENSES, SKILLS } from "../game/data";
import { freshSave, SaveManager } from "../core/SaveManager";
import type { Enemy, EnemyKind, SaveData, Scene } from "../game/types";

const enemyTemplate=(kind:EnemyKind,id:number,x=88):Enemy=>{const t={wretch:[35,.035,6,"#9aae91"],hound:[24,.07,5,"#9b604f"],shade:[28,.045,7,"#765a91"],knight:[55,.025,10,"#737b84"],bat:[18,.08,4,"#b08a9d"],bellbeast:[240,.018,15,"#aa4667"]}[kind] as [number,number,number,string];return{id,kind,x,hp:t[0],maxHp:t[0],speed:t[1],damage:t[2],color:t[3]}};

export function GameClient(){
  const [scene,setScene]=useState<Scene>("title"),[data,setData]=useState<SaveData>(freshSave),[panel,setPanel]=useState<string|null>(null);
  const [hasSave,setHasSave]=useState(false),[mounted,setMounted]=useState(false);
  const [playerX,setPlayerX]=useState(22),[enemies,setEnemies]=useState<Enemy[]>([]),[message,setMessage]=useState(""),[wave,setWave]=useState(0),[boss,setBoss]=useState(false),[paused,setPaused]=useState(false);
  const held=useRef(new Set<string>()),tick=useRef(0),attackLock=useRef(false),dataRef=useRef(data); dataRef.current=data;
  const toast=(m:string)=>{setMessage(m);setTimeout(()=>setMessage(""),2200)};
  const save=useCallback(()=>{SaveManager.save(dataRef.current);setHasSave(true);toast("PROGRESS INSCRIBED")},[]);
  const start=(load=false)=>{const next=load?SaveManager.load():freshSave();if(!next)return toast("NO RECORD FOUND");setData(next);setPlayerX(22);setScene("castle");setPanel(null);toast(load?"WELCOME BACK, WARDEN":"THE KEEP AWAKENS")};
  useEffect(()=>{setHasSave(SaveManager.has());setMounted(true)},[]);
  const spawn=(kinds:EnemyKind[])=>setEnemies(kinds.map((k,i)=>enemyTemplate(k,Date.now()+i,91+i*5)));
  const reward=(e:Enemy)=>{setData(d=>{const kills=(d.bestiary[e.kind]||0)+1;let xp=d.xp+(e.kind==="bellbeast"?140:18),level=d.level,maxHp=d.maxHp,jp=d.jp+(e.kind==="bellbeast"?100:12);if(xp>=level*100){xp-=level*100;level++;maxHp+=12;toast(`WARDEN LEVEL UP — ${level}`)}return{...d,xp,level,maxHp,hp:Math.min(maxHp,d.hp+8),jp,gold:d.gold+10,bestiary:{...d.bestiary,[e.kind]:kills}}});};
  const attack=useCallback(()=>{if(attackLock.current||paused||scene==="title")return;attackLock.current=true;setTimeout(()=>attackLock.current=false,300);let hit=false;setEnemies(es=>es.map(e=>{if(Math.abs(e.x-playerX)<13){hit=true;const dmg=dataRef.current.learned.includes("power")?30:18;return{...e,hp:e.hp-dmg}}return e}).filter(e=>{if(e.hp<=0){reward(e);return false}return true}));if(hit)toast("STEEL STRIKES TRUE")},[paused,playerX,scene]);
  useEffect(()=>{const down=(e:KeyboardEvent)=>{held.current.add(e.key.toLowerCase());if(e.key===" "||e.key.toLowerCase()==="j"){e.preventDefault();attack()}if(e.key==="Escape")setPanel(p=>p?null:"menu")};const up=(e:KeyboardEvent)=>held.current.delete(e.key.toLowerCase());addEventListener("keydown",down);addEventListener("keyup",up);return()=>{removeEventListener("keydown",down);removeEventListener("keyup",up)}},[attack]);
  useEffect(()=>{if(scene==="title"||paused)return;const id=setInterval(()=>{tick.current++;setPlayerX(x=>Math.max(5,Math.min(94,x+(held.current.has("d")||held.current.has("arrowright")?1.2:0)-(held.current.has("a")||held.current.has("arrowleft")?1.2:0))));setEnemies(es=>es.map(e=>({...e,x:e.x-e.speed*5})).filter(e=>{if(e.x<5){setData(d=>({...d,hp:Math.max(0,d.hp-e.damage)}));return false}return true}));if(scene==="defense"&&tick.current%18===0)setEnemies(es=>es.map(e=>({...e,hp:e.hp-Object.keys(dataRef.current.defenses).length*2})).filter(e=>{if(e.hp<=0){reward(e);return false}return true}));},80);return()=>clearInterval(id)},[scene,paused]);
  useEffect(()=>{if(data.hp<=0){toast("THE WARDEN FALLS — RETURNED TO SANCTUARY");setTimeout(()=>{setData(d=>({...d,hp:d.maxHp}));setEnemies([]);setScene("castle")},1200)}},[data.hp]);
  useEffect(()=>{if(scene==="defense"&&wave>0&&enemies.length===0){if(wave<3){const n=wave+1;setWave(n);setTimeout(()=>spawn(n===2?["hound","shade","wretch"]:["knight","wretch","bat"]),900)}else if(!boss){setBoss(true);setTimeout(()=>spawn(["bellbeast"]),1000)}else{setData(d=>({...d,castleLevel:2,castleXp:d.castleXp+100,westernHall:true,gold:d.gold+150}));setScene("castle");setWave(0);setBoss(false);save();toast("CASTLE LEVEL UP — WESTERN HALL UNLOCKED")}}},[enemies.length,scene,wave,boss,save]);
  const enterForest=()=>{setScene("forest");setPlayerX(12);spawn(["hound","shade","bat","wretch"]);toast("EXPEDITION — HAUNTED FOREST")};
  const beginNight=()=>{if(!Object.keys(data.defenses).length)return toast("PLACE A DEFENSE FIRST");setScene("defense");setPlayerX(25);setWave(1);spawn(["wretch","wretch","bat"]);setPanel(null);toast("NIGHT I — HOLD THE GATE")};
  const buySkill=(id:string,cost:number)=>setData(d=>d.jp<cost||d.learned.includes(id)?d:{...d,jp:d.jp-cost,learned:[...d.learned,id]});
  const build=(id:string,cost:number)=>setData(d=>d.gold<cost?d:{...d,gold:d.gold-cost,defenses:{...d.defenses,[id]:(d.defenses[id]||0)+1}});
  const titleCastle=data.castleLevel>1||hasSave;
  const status=useMemo(()=>`LV ${data.level}  HP ${data.hp}/${data.maxHp}  XP ${data.xp}/${data.level*100}  JP ${data.jp}  ✦ ${data.gold}`,[data]);
  if(!mounted)return <main className="game title" aria-label="Loading Castle of the Last Warden"/>;
  return <main className={`game ${scene}`}>
    {scene==="title"?<section className="title-screen"><div className="rain"/><div className={`castle-art ${titleCastle?"restored":""}`}><i/><i/><i/><span>♜</span></div><p className="eyebrow">A GOTHIC ACTION RPG</p><h1>CASTLE <small>OF THE</small><br/>LAST WARDEN</h1><div className="rule">◆</div><nav><button disabled={!hasSave} onClick={()=>start(true)}>CONTINUE</button><button onClick={()=>start(false)}>NEW GAME</button><button onClick={()=>setPanel("load")}>LOAD GAME</button><button onClick={()=>setPanel("settings")}>SETTINGS</button><button onClick={()=>setPanel("archives")}>ARCHIVES</button></nav><footer>VERSION 0.1 · THE AWAKENING</footer></section>:<>
      <header><span>{scene==="castle"?"THE FORSAKEN KEEP":scene==="forest"?"HAUNTED FOREST":"NIGHT DEFENSE"}</span><b>{status}</b><button onClick={()=>setPanel("menu")}>☰</button></header>
      <section className="world"><div className="moon"/><div className="fog"/><div className="room-label">{scene==="castle"?(playerX<32?"FORGE · ELARA":playerX<65?"GREAT HALL":"COURTYARD · NIGHT BELL"):scene==="forest"?"THE WEEPING PATH":"MAIN GATE"}</div>{scene==="castle"&&<><div className="elara">♟<em>ELARA</em></div><div className="bell">♜<em>NIGHT BELL</em></div><div className="locked">▥<em>{data.westernHall?"WESTERN HALL":"SEALED"}</em></div></>}{scene==="defense"&&Object.entries(data.defenses).map(([k,v],i)=><div className="tower" style={{left:`${35+i*13}%`}} key={k}>{DEFENSES.find(d=>d.id===k)?.icon}<em>LV {v}</em></div>)}
        {enemies.map(e=><div className={`enemy ${e.kind}`} style={{left:`${e.x}%`,"--enemy":e.color} as React.CSSProperties} key={e.id}><span>{e.kind==="bellbeast"?"♜":"♟"}</span><i style={{width:`${e.hp/e.maxHp*100}%`}}/><em>{BESTIARY[e.kind].name}</em></div>)}
        <div className="warden" style={{left:`${playerX}%`}}><span>♞</span><i/><em>WARDEN</em></div><div className="ground"/>
      </section>
      <div className="actions">{scene==="castle"&&<><button onClick={()=>setPanel("elara")}>TALK / FORGE</button><button onClick={()=>setPanel("defenses")}>DEFENSES</button><button onClick={()=>setPanel("bell")}>RING BELL</button><button onClick={enterForest}>EXPEDITION</button></>}{scene==="forest"&&<button onClick={()=>{setEnemies([]);setScene("castle");toast("RETURNED TO THE KEEP")}}>RETURN TO CASTLE</button>}<button onClick={attack}>⚔ ATTACK</button></div>
      <div className="touch"><button onPointerDown={()=>held.current.add("a")} onPointerUp={()=>held.current.delete("a")}>◀</button><button onPointerDown={()=>held.current.add("d")} onPointerUp={()=>held.current.delete("d")}>▶</button><button onClick={attack}>⚔</button></div>
    </>}
    {message&&<div className="toast">{message}</div>}{panel&&<div className="overlay" onClick={()=>setPanel(null)}><section className="panel" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setPanel(null)}>×</button><Panel type={panel} data={data} buySkill={buySkill} build={build} save={save} beginNight={beginNight} start={start}/></section></div>}
  </main>
}

function Panel({type,data,buySkill,build,save,beginNight,start}:{type:string,data:SaveData,buySkill:(i:string,c:number)=>void,build:(i:string,c:number)=>void,save:()=>void,beginNight:()=>void,start:(l:boolean)=>void}){
  if(type==="bell")return <><p className="eyebrow">VOLUNTARY ENCOUNTER</p><h2>RING THE NIGHT BELL?</h2><p>Expected threat: Grave Wretches, Shades, Rust Knights and an elite presence.</p><dl><dt>Recommended Castle Level</dt><dd>1</dd><dt>Possible Rewards</dt><dd>Castle XP · 150 Gold · Western Hall</dd></dl><button className="primary" onClick={beginNight}>BEGIN NIGHT</button></>;
  if(type==="defenses")return <><h2>CASTLE DEFENSES</h2><p>Select a ward slot. Built defenses attack automatically while you fight.</p><div className="cards">{DEFENSES.map(d=><article key={d.id}><b>{d.icon} {d.name}</b><p>{d.text}</p><small>LEVEL {data.defenses[d.id]||0} · {d.cost} GOLD</small><button onClick={()=>build(d.id,d.cost)}>{data.defenses[d.id]?"UPGRADE":"BUILD"}</button></article>)}</div></>;
  if(type==="elara")return <><p className="eyebrow">BLACKSMITH · TRUST {data.relationship}/5</p><h2>ELARA VALE</h2><blockquote>“The keep is not dead. Listen—the iron still answers.”</blockquote><p>Elara restores the first defense sockets and keeps your Warden Sword sharp.</p><button onClick={()=>build("crossbow",40)}>FORGE CROSSBOW TURRET · 40</button></>;
  if(type==="archives")return <><h2>BESTIARY ARCHIVES</h2><div className="cards">{Object.entries(BESTIARY).map(([id,b])=><article key={id}><b>{b.name}</b><small>KILLS {data.bestiary[id]||0} · RESEARCH {Math.min(100,(data.bestiary[id]||0)*20)}%</small><p>Weak: {b.weak}<br/>Drop: {b.drop}</p><i>{b.lore}</i></article>)}</div></>;
  if(type==="load")return <><h2>LOAD GAME</h2><article className="save-slot"><b>AUTOSAVE · SLOT I</b><p>{SaveManager.has()?`Warden Lv. ${data.level} · Castle Lv. ${data.castleLevel}`:"Empty record"}</p><button onClick={()=>start(true)}>LOAD</button></article></>;
  if(type==="settings")return <><h2>SETTINGS</h2><label>Music <input type="range" defaultValue="65"/></label><label>SFX <input type="range" defaultValue="80"/></label><label>Ambience <input type="range" defaultValue="70"/></label><label><input type="checkbox" defaultChecked/> Reduced flashes</label><p>Controls: A/D or arrows to move · J/Space to attack · Esc for menu.</p></>;
  return <><h2>WARDEN’S LEDGER</h2><div className="stats"><b>LEVEL {data.level}</b><b>CASTLE LV. {data.castleLevel}</b><b>JP {data.jp}</b><b>GOLD {data.gold}</b></div><h3>DISCIPLINES</h3><div className="cards">{SKILLS.map(s=><article key={s.id}><small>{s.discipline}</small><b>{s.name}</b><p>{s.text}</p><button disabled={data.learned.includes(s.id)||data.jp<s.cost} onClick={()=>buySkill(s.id,s.cost)}>{data.learned.includes(s.id)?"LEARNED":`${s.cost} JP`}</button></article>)}</div><h3>EQUIPMENT</h3><p>Weapon: {data.weapon} · Relic: {data.relic}</p><div className="row"><button onClick={save}>MANUAL SAVE</button><button onClick={()=>location.reload()}>TITLE SCREEN</button></div></>;
}
