"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { BESTIARY, DEFENSES, SKILLS } from "../game/data";
import { freshSave, SaveManager } from "../core/SaveManager";
import type { ActiveEnemy, Enemy, EnemyKind, SaveData, Scene } from "../game/types";
import { BellSprite, DefenseSprite, ElaraSprite, EnemySprite, WardenSprite, type WardenPhase } from "./VisualActors";
import { WorldStage, type StageRoom } from "./WorldStage";
import { AudioManager } from "../core/AudioManager";
import { PlayerController } from "../game/player/PlayerController";
import { PLAYER_MOVEMENT } from "../game/player/PlayerConfig";
import { interactionAt, roomAt, worldToPercent } from "../game/player/RoomDefinitions";

const enemyTemplate=(kind:EnemyKind,id:number,x=88):Enemy=>{const t={wretch:[35,.035,6,"#9aae91"],hound:[24,.07,5,"#9b604f"],shade:[28,.045,7,"#765a91"],knight:[55,.025,10,"#737b84"],bat:[18,.08,4,"#b08a9d"],bellbeast:[240,.018,15,"#aa4667"]}[kind] as [number,number,number,string];return{id,kind,x,hp:t[0],maxHp:t[0],speed:t[1],damage:t[2],color:t[3]}};
const activeEnemy=(kind:EnemyKind,id:number,x=88):ActiveEnemy=>({...enemyTemplate(kind,id,x),phase:"move",phaseUntil:0,rewarded:false});
const roomForAudio=(x:number):StageRoom=>roomAt(x);

export function GameClient(){
  const [controller]=useState(()=>new PlayerController());
  const [scene,setScene]=useState<Scene>("title"),[data,setData]=useState<SaveData>(freshSave),[panel,setPanel]=useState<string|null>(null);
  const [hasSave,setHasSave]=useState(false),[mounted,setMounted]=useState(false);
  const [playerView,setPlayerView]=useState(()=>controller.snapshot()),[enemies,setEnemies]=useState<ActiveEnemy[]>([]),[message,setMessage]=useState(""),[wave,setWave]=useState(0),[boss,setBoss]=useState(false);
  const [wardenPhase,setWardenPhase]=useState<WardenPhase>("idle"),[ringing,setRinging]=useState(false),[menuTab,setMenuTab]=useState("warden"),[defenseFiring,setDefenseFiring]=useState(false),[elaraWorking,setElaraWorking]=useState(false);
  const [impacts,setImpacts]=useState<{id:number;x:number;damage:number}[]>([]);
  const wardenElement=useRef<HTMLDivElement|null>(null),debugElement=useRef<HTMLPreElement|null>(null),tick=useRef(0),attackLock=useRef(false),deadLock=useRef(false),nightCompletion=useRef(false),bossDefeated=useRef(false),dataRef=useRef(data); dataRef.current=data;
  const playerX=worldToPercent(playerView.x);
  const toast=(m:string)=>{setMessage(m);setTimeout(()=>setMessage(""),2200)};
  const save=useCallback(()=>{SaveManager.save(dataRef.current);setHasSave(true);toast("PROGRESS INSCRIBED")},[]);
  const start=(load=false)=>{const next=load?SaveManager.load():freshSave();if(!next)return toast("NO RECORD FOUND");void AudioManager.unlock();AudioManager.sfx("confirm");AudioManager.playScene("castle");controller.reset();setPlayerView(controller.snapshot());setData(next);setScene("castle");setPanel(null);toast(load?"WELCOME BACK, WARDEN":"THE KEEP AWAKENS")};
  useEffect(()=>{setHasSave(SaveManager.has());setMounted(true)},[]);
  useEffect(()=>{const unlock=()=>{void AudioManager.unlock();AudioManager.playScene(scene)};addEventListener("pointerdown",unlock,{once:true});return()=>removeEventListener("pointerdown",unlock)},[scene]);
  useEffect(()=>{if(scene!=="title")AudioManager.playScene(scene)},[scene]);
  useEffect(()=>{if(scene!=="castle"||roomForAudio(playerView.x)!=="forge"||panel==="elara")return;let stopped=false,workTimer=0,impactTimer=0,idleTimer=0;const work=()=>{if(stopped)return;setElaraWorking(true);impactTimer=window.setTimeout(()=>AudioManager.sfx("hammer"),360);idleTimer=window.setTimeout(()=>setElaraWorking(false),980);workTimer=window.setTimeout(work,3000+Math.random()*2200)};workTimer=window.setTimeout(work,800);return()=>{stopped=true;setElaraWorking(false);clearTimeout(workTimer);clearTimeout(impactTimer);clearTimeout(idleTimer)}},[scene,playerView.x,panel]);
  const spawn=(kinds:EnemyKind[])=>setEnemies(kinds.map((k,i)=>activeEnemy(k,Date.now()+i,91+i*5)));
  const reward=useCallback((e:Enemy)=>{if(e.kind==="bellbeast")bossDefeated.current=true;AudioManager.sfx(e.kind==="bellbeast"?"bossDeath":"enemyDeath");setData(d=>{const kills=(d.bestiary[e.kind]||0)+1;let xp=d.xp+(e.kind==="bellbeast"?140:18),level=d.level,maxHp=d.maxHp;const jp=d.jp+(e.kind==="bellbeast"?100:12);if(xp>=level*100){xp-=level*100;level++;maxHp+=12;AudioManager.sfx("level");toast(`WARDEN LEVEL UP — ${level}`)}return{...d,xp,level,maxHp,hp:Math.min(maxHp,d.hp+8),jp,gold:d.gold+10,bestiary:{...d.bestiary,[e.kind]:kills}}});},[]);
  const markDamage=useCallback((amount:number,source:"sword"|"tower")=>{const now=performance.now();setEnemies(es=>es.map(e=>{if(e.phase==="death"||Math.abs(e.x-playerX)>=13&&source==="sword")return e;const hp=e.hp-amount;if(hp<=0){if(!e.rewarded)reward(e);return{...e,hp:0,phase:"death",phaseUntil:now+(e.kind==="bellbeast"?1050:620),rewarded:true}}return{...e,hp,phase:"hurt",phaseUntil:now+(e.kind==="bellbeast"?120:190)}}));},[playerX,reward]);
  const attack=useCallback(()=>{if(attackLock.current||panel||scene==="title"||wardenPhase==="death"||wardenPhase==="hurt")return;attackLock.current=true;setWardenPhase("attack");setTimeout(()=>AudioManager.sfx("sword"),90);setTimeout(()=>{const liveX=worldToPercent(controller.state.x),target=enemies.find(e=>e.phase!=="death"&&Math.abs(e.x-liveX)<13);if(target){const dmg=dataRef.current.learned.includes("power")?30:18;markDamage(dmg,"sword");const impact={id:Date.now(),x:target.x,damage:dmg};setImpacts(v=>[...v,impact]);setTimeout(()=>setImpacts(v=>v.filter(p=>p.id!==impact.id)),420);AudioManager.sfx("hit");toast("STEEL STRIKES TRUE")}},155);setTimeout(()=>{attackLock.current=false;setWardenPhase("idle")},320)},[controller,enemies,markDamage,panel,scene,wardenPhase]);
  const jump=useCallback(()=>{if(panel||scene==="title"||wardenPhase==="death"||wardenPhase==="hurt")return;controller.input.pressJump();AudioManager.sfx("jump")},[controller,panel,scene,wardenPhase]);
  const releaseJump=useCallback(()=>controller.input.releaseJump(),[controller]);
  const releaseDirection=useCallback((pointerId:number)=>controller.input.releasePointer(pointerId),[controller]);
  const clearHeld=useCallback(()=>{controller.input.clear();controller.setEnabled(false)},[controller]);
  useEffect(()=>{if(panel)clearHeld()},[clearHeld,panel]);
  useEffect(()=>{const release=(e:PointerEvent)=>releaseDirection(e.pointerId);addEventListener("pointerup",release);addEventListener("pointercancel",release);return()=>{removeEventListener("pointerup",release);removeEventListener("pointercancel",release)}},[releaseDirection]);
  useEffect(()=>{const down=(e:KeyboardEvent)=>{if(panel)return;controller.input.keyDown(e.key);if(e.key===" "||e.key.toLowerCase()==="j"){e.preventDefault();attack()}if(e.key.toLowerCase()==="w"||e.key==="ArrowUp")jump();if(e.key.toLowerCase()==="b"&&scene==="castle")setPanel("bell");if(e.key.toLowerCase()==="m"&&scene==="castle")setPanel("travel");if(e.key==="Escape")setPanel("menu")};const up=(e:KeyboardEvent)=>{controller.input.keyUp(e.key);if(e.key.toLowerCase()==="w"||e.key==="ArrowUp")releaseJump()};const visibility=()=>{if(document.hidden){clearHeld();AudioManager.suspend()}else void AudioManager.resume()};addEventListener("keydown",down);addEventListener("keyup",up);addEventListener("blur",clearHeld);addEventListener("orientationchange",clearHeld);document.addEventListener("visibilitychange",visibility);return()=>{removeEventListener("keydown",down);removeEventListener("keyup",up);removeEventListener("blur",clearHeld);removeEventListener("orientationchange",clearHeld);document.removeEventListener("visibilitychange",visibility)}},[attack,clearHeld,controller,jump,panel,releaseJump,scene]);
  useEffect(()=>{let frame=0,last=performance.now(),lastPublish=0,lastStep=0,wasGrounded=controller.state.grounded;const loop=(now:number)=>{const rawDt=(now-last)/1000;last=now;if(scene!=="title"&&!panel&&wardenPhase!=="death"){const dt=controller.step(rawDt),state=controller.state,element=wardenElement.current;if(element){element.style.left=`${worldToPercent(state.x)}%`;element.style.bottom=`calc(24% + ${state.y*PLAYER_MOVEMENT.worldToRenderY}px)`}if(debugElement.current)debugElement.current.textContent=`x ${state.x.toFixed(1)}  y ${state.y.toFixed(1)}\nvx ${state.vx.toFixed(1)}  vy ${state.vy.toFixed(1)}\n${state.grounded?"grounded":"airborne"}  ${state.facing}\ninput ${state.inputDirection}  ${(1/Math.max(rawDt,.001)).toFixed(0)} fps  ${(dt*1000).toFixed(1)} ms\nroom ${scene==="castle"?roomAt(state.x):scene}`;if(!wasGrounded&&state.grounded)AudioManager.sfx("land");wasGrounded=state.grounded;if(state.grounded&&Math.abs(state.vx)>30&&now-lastStep>330){AudioManager.sfx("footstep");lastStep=now}if(now-lastPublish>66){setPlayerView(controller.snapshot());lastPublish=now}}frame=requestAnimationFrame(loop)};frame=requestAnimationFrame(loop);return()=>cancelAnimationFrame(frame)},[controller,panel,scene,wardenPhase]);
  useEffect(()=>{if(scene==="title"||panel)return;const id=setInterval(()=>{tick.current++;const now=performance.now();setEnemies(es=>es.flatMap(e=>{if(e.phase==="death")return now>=e.phaseUntil?[]:[e];if(e.phase==="hurt")return now>=e.phaseUntil?[{...e,phase:"move" as const}]:[e];if(e.phase==="attack"){if(now<e.phaseUntil)return[e];setData(d=>({...d,hp:Math.max(0,d.hp-e.damage)}));setWardenPhase("hurt");AudioManager.sfx("playerHurt");setTimeout(()=>setWardenPhase(p=>p==="hurt"?"idle":p),260);return[{...e,phase:"death" as const,phaseUntil:now+220,rewarded:true}]};const nextX=e.x-e.speed*5;if(nextX<=5.5)return[{...e,x:5.5,phase:"attack" as const,phaseUntil:now+360}];return[{...e,x:nextX,phase:"move" as const}]}));if(scene==="defense"&&tick.current%18===0&&Object.keys(dataRef.current.defenses).length){setDefenseFiring(true);AudioManager.sfx("tower");markDamage(Object.keys(dataRef.current.defenses).length*2,"tower");setTimeout(()=>setDefenseFiring(false),180)}},80);return()=>clearInterval(id)},[markDamage,panel,scene]);
  useEffect(()=>{if(data.hp<=0&&!deadLock.current){deadLock.current=true;clearHeld();setWardenPhase("death");AudioManager.sfx("playerDeath");toast("THE WARDEN FALLS — RETURNED TO SANCTUARY");setTimeout(()=>{controller.reset();setPlayerView(controller.snapshot());setData(d=>({...d,hp:d.maxHp}));setEnemies([]);setScene("castle");setWardenPhase("idle");deadLock.current=false},1250)}},[clearHeld,controller,data.hp]);
  useEffect(()=>{if(scene==="defense"&&wave>0&&enemies.length===0){if(wave<3){const n=wave+1;setWave(n);setTimeout(()=>spawn(n===2?["hound","shade","wretch"]:["knight","wretch","bat"]),900)}else if(!boss){setBoss(true);toast("THE BELL TOWER BEAST");AudioManager.sfx("bossIntro");setTimeout(()=>spawn(["bellbeast"]),1000)}else if(bossDefeated.current&&!nightCompletion.current){nightCompletion.current=true;setData(d=>{const next={...d,castleLevel:2,castleXp:d.castleXp+100,westernHall:true,gold:d.gold+150};SaveManager.save(next);return next});setHasSave(true);setScene("castle");setWave(0);setBoss(false);toast("CASTLE LEVEL UP — WESTERN HALL UNLOCKED")}}},[enemies.length,scene,wave,boss]);
  const enterForest=()=>{controller.reset(120);setPlayerView(controller.snapshot());setPanel(null);setScene("forest");spawn(["hound","shade","bat","wretch"]);toast("EXPEDITION — HAUNTED FOREST")};
  const beginNight=()=>{if(!Object.keys(data.defenses).length)return toast("PLACE A DEFENSE FIRST");nightCompletion.current=false;bossDefeated.current=false;AudioManager.duck(900);setRinging(true);setPanel(null);toast("THE NIGHT BELL TOLLS");setTimeout(()=>AudioManager.sfx("bell"),170);setTimeout(()=>{controller.reset(250);setPlayerView(controller.snapshot());setRinging(false);setScene("defense");AudioManager.playScene("defense");setWave(1);spawn(["wretch","wretch","bat"]);toast("NIGHT I — HOLD THE GATE")},900)};
  const buySkill=(id:string,cost:number)=>setData(d=>{if(d.jp<cost||d.learned.includes(id))return d;AudioManager.sfx("learn");return{...d,jp:d.jp-cost,learned:[...d.learned,id]}});
  const build=(id:string,cost:number)=>setData(d=>d.gold<cost?d:{...d,gold:d.gold-cost,defenses:{...d.defenses,[id]:(d.defenses[id]||0)+1}});
  const titleCastle=data.castleLevel>1||hasSave;
  const hpPct=Math.max(0,data.hp/data.maxHp*100),xpPct=Math.min(100,data.xp/(data.level*100)*100);
  const room:StageRoom=scene==="forest"?"forest":scene==="defense"?"gate":roomAt(playerView.x),interaction=interactionAt(playerView.x,data.westernHall);
  const context=scene==="castle"?(interaction==="elara"?{label:"TALK TO ELARA",action:()=>setPanel("elara")} : interaction==="bell"?{label:"RING NIGHT BELL",action:()=>setPanel("bell")} : interaction==="western"||interaction==="sealed"?{label:data.westernHall?"ENTER WESTERN HALL":"SEALED BY THE WARDEN CREST",action:()=>toast(data.westernHall?"WESTERN HALL":"THE CREST DOES NOT ANSWER")} : {label:"OPEN CASTLE MAP",action:()=>setPanel("travel")}) : scene==="forest"?{label:"RETURN TO CASTLE",action:()=>{controller.reset();setPlayerView(controller.snapshot());setEnemies([]);setScene("castle");toast("RETURNED TO THE KEEP")}}:null;
  const visualPhase:WardenPhase=wardenPhase==="attack"||wardenPhase==="hurt"||wardenPhase==="death"?wardenPhase:playerView.movementMode;
  const movementDebug=mounted&&typeof location!=="undefined"&&new URLSearchParams(location.search).get("debugMovement")==="1";
  if(!mounted)return <main className="game title" aria-label="Loading Castle of the Last Warden"/>;
  return <main className={`game ${scene} room-${room} ${ringing?"bell-transition":""}`}>
    {scene==="title"?<TitleScreen hasSave={hasSave} restored={titleCastle} start={start} open={setPanel}/>:<>
      <header className="hud"><div className="hud-identity"><span className="hud-crest">W</span><div><b>THE WARDEN</b><small>LEVEL {data.level}</small></div></div><div className="hud-bars"><label>HP <i><u style={{width:`${hpPct}%`}}/></i><em>{data.hp}/{data.maxHp}</em></label><label>XP <i><u style={{width:`${xpPct}%`}}/></i><em>{data.xp}/{data.level*100}</em></label></div><div className="hud-currency"><b>JP {data.jp}</b><span>{data.gold} G</span></div><div className="hud-location"><small>{scene==="castle"?"THE FORSAKEN KEEP":scene==="forest"?"EXPEDITION":"NIGHT DEFENSE"}</small><b>{room==="forge"?"ELARA'S FORGE":room==="hall"?"GREAT HALL":room==="courtyard"?"MOON COURTYARD":room==="forest"?"THE WEEPING PATH":"MAIN GATE"}</b></div><button className="menu-button" aria-label="Open Warden menu" onClick={()=>setPanel("menu")}><i/><i/><i/></button></header>
      <section className="world"><WorldStage room={room} night={scene==="defense"} restored={data.castleLevel>1}/>{scene==="castle"&&room==="forge"&&<div className="elara actor-wrap"><ElaraSprite talking={panel==="elara"} working={elaraWorking}/><em><b>!</b> ELARA · BLACKSMITH</em></div>}{scene==="castle"&&room==="courtyard"&&<><div className="bell actor-wrap"><BellSprite ringing={ringing}/><em>NIGHT BELL</em></div><div className={`locked actor-wrap ${data.westernHall?"unlocked":""}`}><span className="seal-gate"><i/><i/><i/></span><em>{data.westernHall?"WESTERN HALL":"WARDEN SEAL"}</em></div></>}{scene==="defense"&&Object.entries(data.defenses).map(([k,v],i)=><div className="tower actor-wrap" style={{left:`${35+i*13}%`}} key={k}><DefenseSprite kind={k} firing={defenseFiring}/><em>{DEFENSES.find(d=>d.id===k)?.name} · LV {v}</em></div>)}
        {enemies.map(e=><div className={`enemy actor-wrap ${e.kind} phase-${e.phase}`} style={{left:`${e.x}%`,"--enemy":e.color} as React.CSSProperties} key={e.id}><EnemySprite kind={e.kind} phase={e.phase}/><i className="enemy-hp"><u style={{width:`${e.hp/e.maxHp*100}%`}}/></i><em>{BESTIARY[e.kind].name}</em></div>)}
        {impacts.map(p=><div className="hit-impact" style={{left:`${p.x}%`}} key={p.id}><i/><b>{p.damage}</b></div>)}
        <div ref={wardenElement} className={`warden actor-wrap phase-${visualPhase} facing-${playerView.facing}`} style={{left:`${playerX}%`,bottom:`calc(24% + ${playerView.y*PLAYER_MOVEMENT.worldToRenderY}px)`}}><WardenSprite phase={visualPhase}/></div><div className="ground"/>{boss&&scene==="defense"&&<div className="boss-card"><small>THE BELL TOWER STIRS</small><b>BELL TOWER BEAST</b></div>}{movementDebug&&<pre ref={debugElement} className="movement-debug"/>}
      </section>
      {context&&<button className="context-action" onClick={context.action}><span>INTERACT</span>{context.label}</button>}
      <button className="quick-defense" onClick={()=>setPanel("defenses")} aria-label="Manage castle defenses"><i/>DEFENSES</button>
      <div className="touch touch-left"><button aria-label="Move left" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);controller.input.holdDirection(e.pointerId,-1)}} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)releaseDirection(e.pointerId)}} onPointerUp={e=>releaseDirection(e.pointerId)} onPointerLeave={e=>releaseDirection(e.pointerId)} onPointerCancel={e=>releaseDirection(e.pointerId)} onLostPointerCapture={e=>releaseDirection(e.pointerId)}><i className="arrow-left"/></button><button aria-label="Move right" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);controller.input.holdDirection(e.pointerId,1)}} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)releaseDirection(e.pointerId)}} onPointerUp={e=>releaseDirection(e.pointerId)} onPointerLeave={e=>releaseDirection(e.pointerId)} onPointerCancel={e=>releaseDirection(e.pointerId)} onLostPointerCapture={e=>releaseDirection(e.pointerId)}><i className="arrow-right"/></button></div>
      <div className="touch touch-right"><button className="jump-control" aria-label="Jump" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);jump()}} onPointerUp={releaseJump} onPointerCancel={releaseJump} onLostPointerCapture={releaseJump}><i className="jump-icon"/></button><button className="attack-control" aria-label="Attack" onClick={attack}><i className="blade-icon"/></button></div>
      <div className="rotate-notice"><span className="phone-icon"/><b>ROTATE YOUR DEVICE</b><small>Landscape is the intended way to defend the keep.</small></div>
    </>}
    {message&&<div className="toast"><i/>{message}</div>}{panel&&<div className="overlay" onClick={()=>setPanel(null)}><section className="panel" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close menu" onClick={()=>setPanel(null)}>×</button><Panel type={panel} data={data} buySkill={buySkill} build={build} save={save} beginNight={beginNight} start={start} enterForest={enterForest} tab={menuTab} setTab={setMenuTab}/></section></div>}
  </main>
}

function TitleScreen({hasSave,restored,start,open}:{hasSave:boolean;restored:boolean;start:(l:boolean)=>void;open:(p:string)=>void}){return <section className="title-screen"><div className="title-backdrop"/><div className="title-mist mist-a"/><div className="title-mist mist-b"/><div className="title-rain"/><div className={`title-castle ${restored?"restored":""}`}><i className="tower-a"/><i className="tower-b"/><i className="keep"/><i className="bridge"/><span/><span/><span/><span/></div><div className="title-copy"><p className="eyebrow">THE ORDER HAS FALLEN · THE BELL REMAINS</p><h1>CASTLE <small>OF THE</small><br/><strong>LAST WARDEN</strong></h1><div className="title-sigil"><i/>W<i/></div><nav><button disabled={!hasSave} onClick={()=>start(true)}>CONTINUE</button><button onClick={()=>start(false)}>NEW GAME</button><button onClick={()=>open("load")}>LOAD GAME</button><button onClick={()=>open("settings")}>SETTINGS</button><button onClick={()=>open("archives")}>ARCHIVES</button><button onClick={()=>open("credits")}>CREDITS</button></nav></div><footer>VERSION 0.1 · THE AWAKENING</footer></section>}

function Panel({type,data,buySkill,build,save,beginNight,start,enterForest,tab,setTab}:{type:string;data:SaveData;buySkill:(i:string,c:number)=>void;build:(i:string,c:number)=>void;save:()=>void;beginNight:()=>void;start:(l:boolean)=>void;enterForest:()=>void;tab:string;setTab:(t:string)=>void}){
  if(type==="bell")return <div className="bell-panel"><p className="eyebrow">VOLUNTARY ENCOUNTER</p><h2>RING THE NIGHT BELL?</h2><div className="panel-bell"><BellSprite/></div><p>Night falls only by your command. The gates will close and every prepared ward will awaken.</p><dl><dt>EXPECTED THREAT</dt><dd>Wretches · Shades · Rust Knights</dd><dt>RECOMMENDED CASTLE LEVEL</dt><dd>1</dd><dt>POSSIBLE REWARDS</dt><dd>Castle XP · 150 Gold · Western Hall</dd></dl><button className="primary" onClick={beginNight}>BEGIN NIGHT</button></div>;
  if(type==="defenses")return <><p className="eyebrow">ORIN'S WARD TABLE</p><h2>CASTLE DEFENSES</h2><p>Ward sockets answer to the restored mechanisms. Existing costs and strength are unchanged.</p><div className="defense-cards">{DEFENSES.map(d=><article key={d.id}><DefenseSprite kind={d.id}/><div><b>{d.name}</b><p>{d.text}</p><small>LEVEL {data.defenses[d.id]||0} · {d.cost} GOLD</small></div><button onClick={()=>build(d.id,d.cost)}>{data.defenses[d.id]?"UPGRADE":"BUILD"}</button></article>)}</div></>;
  if(type==="elara")return <div className="npc-panel"><div className="npc-portrait"><ElaraSprite talking/><span>BLACKSMITH</span></div><div><p className="eyebrow">TRUST {data.relationship}/5</p><h2>ELARA VALE</h2><blockquote>“The keep is not dead. Listen—the iron still answers.”</blockquote><p>Elara restores the first defense sockets and keeps your Warden Sword sharp. Beyond her, the forge breathes like a living heart.</p><button onClick={()=>build("crossbow",40)}>FORGE CROSSBOW TURRET · 40 GOLD</button></div></div>;
  if(type==="archives")return <><p className="eyebrow">THE WARDEN ARCHIVES</p><h2>BESTIARY</h2><div className="bestiary-grid">{Object.entries(BESTIARY).map(([id,b])=><article key={id}><div className="bestiary-sprite"><EnemySprite kind={id as EnemyKind}/></div><div><b>{b.name}</b><small>KILLS {data.bestiary[id]||0}</small><i className="research"><u style={{width:`${Math.min(100,(data.bestiary[id]||0)*20)}%`}}/></i><small>RESEARCH {Math.min(100,(data.bestiary[id]||0)*20)}%</small><p>Weak: {b.weak} · Drop: {b.drop}</p><em>{b.lore}</em></div></article>)}</div></>;
  if(type==="load")return <><p className="eyebrow">WARDEN RECORDS</p><h2>LOAD GAME</h2><article className="save-slot"><div className="save-preview"><WorldStage room="hall" restored={data.castleLevel>1}/></div><div><b>AUTOSAVE · SLOT I</b><p>{SaveManager.has()?`Warden Lv. ${data.level} · Castle Lv. ${data.castleLevel}`:"Empty record"}</p><small>THE FORSAKEN KEEP · {new Date(data.savedAt).toLocaleString()}</small></div><button onClick={()=>start(true)}>LOAD</button></article></>;
  if(type==="settings")return <><p className="eyebrow">PREFERENCES</p><h2>SETTINGS</h2><div className="settings-grid"><label>Music <input type="range" defaultValue="65" onChange={e=>AudioManager.setVolume("music",Number(e.currentTarget.value)/100)}/></label><label>SFX <input type="range" defaultValue="80" onChange={e=>AudioManager.setVolume("sfx",Number(e.currentTarget.value)/100)}/></label><label>Ambience <input type="range" defaultValue="70" onChange={e=>AudioManager.setVolume("ambience",Number(e.currentTarget.value)/100)}/></label><label><input type="checkbox" defaultChecked/> Reduced flashes and shake</label></div><p>Controls: A/D or arrows to move · W/Up to jump · J/Space to attack · Esc for menu.</p></>;
  if(type==="travel")return <><p className="eyebrow">EXPEDITION MAP</p><h2>BEYOND THE KEEP</h2><article className="travel-card"><div className="travel-art"/><div><b>THE HAUNTED FOREST</b><p>The Weeping Path winds beneath the ruined castle. Warden scouts marked a sealed waystone and an abandoned chest.</p><button onClick={enterForest}>BEGIN EXPEDITION</button></div></article></>;
  if(type==="credits")return <><p className="eyebrow">THE AWAKENING</p><h2>CREDITS</h2><p>Original game design, writing, interface and implementation for Castle of the Last Warden.</p><p>Original pixel-art visual anchor and environment imagery generated specifically for this project with OpenAI image generation, then integrated and adapted for the game. No third-party game sprites, maps, music or proprietary assets are included.</p></>;
  const tabs=["warden","equipment","disciplines","inventory","castle","bestiary","save"];
  return <div className="ledger"><aside><div className="ledger-mark">W</div>{tabs.map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t.toUpperCase()}</button>)}</aside><div className="ledger-content"><p className="eyebrow">THE WARDEN'S LEDGER</p>{tab==="warden"&&<><h2>THE LAST WARDEN</h2><div className="warden-sheet"><div className="full-warden"><WardenSprite attacking={false}/></div><div className="sheet-stats"><b>LEVEL {data.level}</b><span>HP {data.hp} / {data.maxHp}</span><span>XP {data.xp} / {data.level*100}</span><span>JP {data.jp}</span><span>GOLD {data.gold}</span><span>CASTLE LV. {data.castleLevel}</span></div></div></>}{tab==="equipment"&&<><h2>EQUIPMENT</h2><div className="equipment-layout"><div className="slot-list"><button>WEAPON <b>{data.weapon}</b></button><button>BODY <b>Pilgrim Coat</b></button><button>RELIC <b>{data.relic}</b></button></div><article><small>EQUIPPED WEAPON</small><h3>{data.weapon.toUpperCase()}</h3><p>A plain order blade recovered from the Warden's quarters. Its fuller bears a crest worn smooth by time.</p><b>ATK 18</b></article></div></>}{tab==="disciplines"&&<><h2>DISCIPLINES <small>{data.jp} JP AVAILABLE</small></h2><div className="skill-tree">{SKILLS.map(s=><article className={data.learned.includes(s.id)?"learned":""} key={s.id}><small>{s.discipline}</small><b>{s.name}</b><p>{s.text}</p><button disabled={data.learned.includes(s.id)||data.jp<s.cost} onClick={()=>buySkill(s.id,s.cost)}>{data.learned.includes(s.id)?"LEARNED":`${s.cost} JP`}</button></article>)}</div></>}{tab==="inventory"&&<><h2>INVENTORY</h2><div className="inventory-list">{data.inventory.map((item,i)=><button key={item}><i className={`item-icon item-${i}`}/><b>{item}</b><small>{i===0?"FINE WEAPON":i===2?"RELIC":"OWNED"}</small></button>)}</div></>}{tab==="castle"&&<><h2>THE FORSAKEN KEEP</h2><div className="castle-progress"><b>CASTLE LEVEL {data.castleLevel}</b><i><u style={{width:`${Math.min(100,data.castleXp)}%`}}/></i><p>{data.westernHall?"Western Hall restored. The keep's first wounds are closing.":"The Western Hall remains sealed behind the ancient crest."}</p></div></>}{tab==="bestiary"&&<><h2>BESTIARY</h2><button onClick={()=>location.hash="archives"}>Research records are available from the title Archives.</button></>}{tab==="save"&&<><h2>SAVE THE KEEP</h2><p>Inscribe the current Warden, castle, inventory and research state into the existing versioned record.</p><button className="primary" onClick={save}>MANUAL SAVE</button><button onClick={()=>location.reload()}>RETURN TO TITLE</button></>}</div></div>;
}
