type Bus="music"|"sfx"|"ambience";
class OriginalAudioManager{
  private ctx:AudioContext|null=null; private master:GainNode|null=null; private buses:Record<Bus,GainNode|null>={music:null,sfx:null,ambience:null}; private musicTimer:number|null=null; private scene="";
  private ensure(){if(this.ctx)return this.ctx; const AC=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext;if(!AC)return null;this.ctx=new AC();this.master=this.ctx.createGain();this.master.gain.value=.55;this.master.connect(this.ctx.destination);for(const key of Object.keys(this.buses) as Bus[]){const g=this.ctx.createGain();g.gain.value=key==="music"?.28:key==="ambience"?.2:.55;g.connect(this.master);this.buses[key]=g}return this.ctx}
  async unlock(){const c=this.ensure();if(c?.state==="suspended")await c.resume().catch(()=>undefined);if(c?.state==="running")document.documentElement.dataset.audio="running"}
  setVolume(bus:Bus|"master",value:number){this.ensure();const g=bus==="master"?this.master:this.buses[bus];if(g&&this.ctx)g.gain.setTargetAtTime(Math.max(0,Math.min(1,value)),this.ctx.currentTime,.03)}
  private tone(freq:number,duration:number,bus:Bus="sfx",wave:OscillatorType="sine",gain=.12,delay=0){const c=this.ensure(),out=this.buses[bus];if(!c||!out)return;const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type=wave;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(gain,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(out);o.start(t);o.stop(t+duration+.03)}
  sfx(name:string){void this.unlock();const map:Record<string,()=>void>={sword:()=>{this.tone(240,.12,"sfx","sawtooth",.08);this.tone(520,.08,"sfx","triangle",.06,.03)},hit:()=>{this.tone(90,.1,"sfx","square",.11);this.tone(760,.06,"sfx","triangle",.06)},jump:()=>this.tone(330,.16,"sfx","triangle",.07),menu:()=>this.tone(620,.07,"sfx","sine",.05),confirm:()=>{this.tone(520,.09,"sfx","triangle",.06);this.tone(780,.12,"sfx","triangle",.05,.07)},bell:()=>{[110,165,220,275].forEach((f,i)=>this.tone(f,2.8,"sfx","sine",.13/(i+1),i*.02))},hammer:()=>{this.tone(145,.12,"ambience","square",.09);this.tone(940,.08,"ambience","triangle",.04)},level:()=>[392,523,659,784].forEach((f,i)=>this.tone(f,.25,"sfx","triangle",.06,i*.09)),death:()=>{this.tone(140,.5,"sfx","sawtooth",.08);this.tone(70,.8,"sfx","sine",.1,.15)},tower:()=>this.tone(430,.08,"sfx","square",.06),fire:()=>this.tone(180,.3,"sfx","sawtooth",.05),holy:()=>[660,880].forEach((f,i)=>this.tone(f,.35,"sfx","sine",.05,i*.08))};map[name]?.()}
  playScene(scene:string){if(this.scene===scene)return;this.scene=scene;void this.unlock();if(this.musicTimer)window.clearInterval(this.musicTimer);const scores:Record<string,{notes:number[];beat:number;wave:OscillatorType}>={title:{notes:[220,261.6,329.6,293.7,246.9,220,196,164.8],beat:900,wave:"triangle"},castle:{notes:[146.8,196,220,174.6,164.8,196,146.8,130.8],beat:1150,wave:"sine"},forest:{notes:[164.8,155.6,196,185,146.8,138.6,164.8,123.5],beat:880,wave:"sine"},defense:{notes:[110,146.8,164.8,196,110,174.6,164.8,146.8],beat:430,wave:"sawtooth"}};const score=scores[scene]||scores.castle;let i=0;const play=()=>{this.tone(score.notes[i%score.notes.length],score.beat/1000*.78,"music",score.wave,.045);if(i%4===0)this.tone(score.notes[i%score.notes.length]/2,score.beat/1000*1.8,"music","sine",.055);i++};play();this.musicTimer=window.setInterval(play,score.beat)}
}
export const AudioManager=new OriginalAudioManager();
